[package]
name = "df_image_carver"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.6", features = ["derive"] }
miette = { version = "7.2.0", features = ["fancy"] }

ringbuf = "0.4.1"
humansize = "2.1.3"
